#eejj
python plot_eejj_finalSelection.py
#python plot_eejj_finalSelection_bestFit.py
python plot_eejj_finalSelection_nMinus1.py
#python plot_eejj_finalSelection_nMinus1_bestFit.py
python plot_eejj_preselection.py

#enujj
python plot_enujj_finalSelection.py
#python plot_enujj_finalSelection_bestFit.py
python plot_enujj_finalSelection_nMinus1.py
#python plot_enujj_finalSelection_nMinus1_bestFit.py
python plot_enujj_preselection.py
